# Generated by Django 5.0.3 on 2024-04-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
