# Generated by Django 5.0.3 on 2024-04-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_fertilizer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='DAP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='muriate_of_potash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='nitro_phosphate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='sugar_phosphate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='urea',
            field=models.IntegerField(default=0),
        ),
    ]
