# Generated by Django 5.0.3 on 2024-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_fertilizer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='desc',
            field=models.TextField(default='A'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='image',
            field=models.ImageField(default='ok.jpg', upload_to='images/'),
        ),
    ]
