# Generated by Django 5.0.3 on 2024-04-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_crops_desc_alter_fertilizer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='desc',
            field=models.TextField(default='A'),
        ),
    ]
