# Generated by Django 5.0.3 on 2024-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_fertilizer_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a', max_length=50)),
                ('summer', models.TextField(default='a')),
                ('monsoon', models.TextField(default='a')),
                ('post_monsoon', models.TextField(default='a')),
                ('winter', models.TextField(default='a')),
            ],
        ),
    ]
