# Generated by Django 5.0.3 on 2024-04-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('web', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
